apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gl-mailer-list-server.fullname" . }}
  labels:
    {{- include "gl-mailer-list-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gl-mailer-list-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gl-mailer-list-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gl-mailer-list-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_ENV
              value: {{ .Values.app.env }}
            - name: DB_HOST
              value: rds
            - name: DB_NAME
              value: {{ .Values.db.name }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds
                  key: password
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-ses
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-ses
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              value: ap-south-1
            - name: AWS_SENDER_EMAIL
              value: {{ .Values.email.sender }}
            - name: AWS_RECIEVER_EMAIL
              value: {{ .Values.email.receiver }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          startupProbe:
            failureThreshold: 60
            periodSeconds: 10
            httpGet:
              path: /ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
