apiVersion: v1
kind: Service
metadata:
  name: {{include "gl-mailer-list-server.fullname" .}}
  labels: {{- include "gl-mailer-list-server.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "gl-mailer-list-server.selectorLabels" . | nindent 4}}
